name: {{ cookiecutter.project_name }}{% raw %} CI

on:
  push:
    branches:
      - main
      - 'stable/**'

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - uses: pre-commit/action@v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  test-sqlite:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11']
        django: ['3.2', '4.0', '4.1', '4.2']
        wagtail: ['4.1', '4.2', '5.0', '5.1']
        exclude:
          - django: '4.0'
            wagtail: '5.0'
          - django: '4.0'
            wagtail: '5.1'
          - django: '4.2'
            wagtail: '4.1'
          - django: '4.2'
            wagtail: '4.2'

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade tox
      - name: Test
        run: |
          tox
        env:
          TOXENV: python${{ matrix.python }}-django${{ matrix.django }}-wagtail${{ matrix.wagtail }}-sqlite

  test-postgres:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11']
        django: ['3.2', '4.0', '4.1', '4.2']
        wagtail: ['4.1', '4.2', '5.0', '5.1']
        experimental: [false]
        exclude:
          - django: '4.0'
            wagtail: '5.0'
          - django: '4.0'
            wagtail: '5.1'
          - django: '4.2'
            wagtail: '4.1'
          - django: '4.2'
            wagtail: '4.2'

    services:
      postgres:
        image: ${{ matrix.postgres || 'postgres:11' }}
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade tox
      - name: Test
        run: |
          tox
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/{% endraw %}{{ cookiecutter.__project_name_snake }}{% raw %}
          TOXENV: python${{ matrix.python }}-django${{ matrix.django }}-wagtail${{ matrix.wagtail }}-postgres{% endraw %}
