# Configuration file for `prek`, a git hook framework.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

ci = { autofix_prs = false }
default_language_version = { python = "python3" }

[[repos]]
repo = "builtin"
hooks = [
  { id = "check-added-large-files" },
  { id = "check-case-conflict" },
  { id = "check-executables-have-shebangs" },
  { id = "check-illegal-windows-names" },
  { id = "check-json" },
  { id = "check-merge-conflict" },
  { id = "check-shebang-scripts-are-executable" },
  { id = "check-symlinks" },
  { id = "check-toml" },
  { id = "check-yaml" },
  { id = "end-of-file-fixer" },
  { id = "trailing-whitespace" },
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "ruff-check"
name = "ruff-check"
entry = "uv run ruff check --force-exclude"
language = "system"
types = ["python"]

[[repos.hooks]]
id = "ruff-format"
name = "ruff-format"
entry = "uv run ruff format --force-exclude"
language = "system"
types_or = ["python"]

[[repos.hooks]]
id = "lint-format"
name = "npm run lint:format"
entry = "npm run lint:format"
language = "system"
types_or = ["css", "scss", "javascript", "ts", "tsx", "json", "yaml"]

[[repos.hooks]]
id = "lint-css"
name = "npm run lint:css"
entry = "npm run lint:css"
language = "system"
types_or = ["css", "scss"]
