ci:
  autofix_prs: false

default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args: ['--unsafe']
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # ruff config is in ruff.toml
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
{%- if cookiecutter.use_frontend in ['y', 'yes'] %}
  - repo: https://github.com/pre-commit/mirrors-prettier
    # prettier config is in prettier.config.js
    rev: 'v2.7.1'
    hooks:
      - id: prettier
        types_or: [css, scss, javascript, ts, tsx, json, yaml]
  - repo: https://github.com/pre-commit/mirrors-eslint
    # eslint config is in .eslintrc.js
    rev: v8.32.0
    hooks:
      - id: eslint
        additional_dependencies:
          - 'eslint@8.49.0'
          - 'eslint-config-airbnb@19.0.4'
          - 'eslint-plugin-import@2.28.1'
          - 'eslint-plugin-jsx-a11y@6.7.1'
          - 'eslint-plugin-react@7.33.2'
          - 'eslint-plugin-react-hooks@4.6.0'
          - '@typescript-eslint/eslint-plugin@6.7.2'
          - '@typescript-eslint/parser@6.7.2'
          - '@wagtail/eslint-config-wagtail@0.4.0'
        files: \.(js|jsx|ts|tsx)$
        types: [file]
  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    # stylelint config is in .stylelintrc.js
    rev: 8f63da497580898a7e0ceef6bf9e72cc0af07828
    hooks:
      - id: stylelint
        files: \.(scss)$
        additional_dependencies:
          - 'stylelint@14.16.1'
          - '@wagtail/stylelint-config-wagtail@0.6.0'
{%- endif %}
