# See https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
# for a detailed guide
name: Publish to PyPI

on:
  release:
    # https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#release
    types: [published]

jobs:
  test:
    uses: ./.github/workflows/test.yml
  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          python-version-file: .python-version
      - run: uv build
      # Smoke tests with ready-to-publish package.
      - run: uv run --isolated --no-project --with dist/*.whl pytest
      - run: uv run --isolated --no-project --with dist/*.tar.gz pytest
      - uses: actions/upload-artifact@v7
        with:
          path: ./dist
  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: none
      id-token: write # required for trusted publishing
    environment: pypi
    steps:
      - uses: actions/download-artifact@v7
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: artifact/
          print-hash: true
