name: Template checks

on: [push, pull_request]

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: uvx cookiecutter . --no-input
      - run: tree wagtail-cool-project
      # Ensure package can be installed
      - run: uv sync --dev
