name: Template checks

on: [push, pull_request]

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
      - run: uvx cookiecutter . --no-input
      - run: tree wagtail-cool-project
      # Ensure package can be installed
      - run: uv sync --dev
