name: CI

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.12'
      - uses: pre-commit/action@v3.0.1
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
      - run: npm ci
      - run: npm run lint

  test-sqlite:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python }}
      - run: uv sync --dev
      - run: uv run tox
        env:
          DB: sqlite

  test-postgres:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11', '3.12']

    services:
      postgres:
        image: ${{ matrix.postgres || 'postgres:12' }}
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python }}
      - run: uv sync --dev
      - run: uv run tox
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/my_project_name
          DB: postgres
